### ISSUE TITLE
Make this an official helm chart

### ISSUE THREAD

**Issue by monotek** [dcwangmit01/helm-fluentd-elasticsearch#1]
I'm wondering why there is no fluentd-elasticsearch helm chart in the official repo. 

https://github.com/kubernetes/charts

Would you mind to do a pull request there?

**Comment by dcwangmit01** [comment]
Hi @monotek,

I thought the same about sumitting a PR to the official charts repo, but the problem is that the docker image on which this chart is based doesn't seem to be public.  I can't seem to find the Dockerfile for it.  In addition, the docker image seems to be rebuilt/released on the whim of google.

repository: gcr.io/google_containers/fluentd-elasticsearch

At one point, i tried to upgrade the chart to v2.0.1, but something about the interface changed.  Without docs, or the original dockerfile or the code, this chart is stuck on the 1.x series.

tag: 1.24 # 1.22 # v2.0.1 is the latest

If you have any ideas, let me know.

-dave

**Comment by monotek** [comment]
I've submitted one by myself now :-)
https://github.com/kubernetes/charts/pull/3379

**Comment by dcwangmit01** [comment]
Nice work André ;)
